# Shell variables
# Generated by 'wal'
wallpaper='/home/metwas/Pictures/wallpapers/windows-11-flow-dark-mode-dark-background-pink-3440x1440-5747.jpg'

# Special
background='#0F0317'
foreground='#d99dca'
cursor='#d99dca'

# Colors
color0='#0F0317'
color1='#900012'
color2='#A20128'
color3='#A30959'
color4='#C3284F'
color5='#CE0561'
color6='#77308A'
color7='#d99dca'
color8='#976d8d'
color9='#900012'
color10='#A20128'
color11='#A30959'
color12='#C3284F'
color13='#CE0561'
color14='#77308A'
color15='#d99dca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
