#!/bin/bash

sudo pacman -S --needed --noconfirm kitty
sudo pacman -S --needed --noconfirm fastfetch
sudo pacman -S --needed --noconfirm base-devel
sudo pacman -S --needed --noconfirm ninja
sudo pacman -S --needed --noconfirm clang
sudo pacman -S --needed --noconfirm gcc
sudo pacman -S --needed --noconfirm git
sudo pacman -S --needed --noconfirm make
sudo pacman -S --needed --noconfirm ncurses
sudo pacman -S --needed --noconfirm flex
sudo pacman -S --needed --noconfirm bison
sudo pacman -S --needed --noconfirm gperf
sudo pacman -S --needed --noconfirm zsh
sudo pacman -S --needed --noconfirm fzf
sudo pacman -S --needed --noconfirm wireshark-cli
sudo pacman -S --needed --noconfirm zip
sudo pacman -S --needed --noconfirm unzip
sudo pacman -S --needed --noconfirm rar
sudo pacman -S --needed --noconfirm conky
sudo pacman -S --needed --noconfirm cmatrix
sudo pacman -S --needed --noconfirm btop
sudo pacman -S --needed --noconfirm go
sudo pacman -S --needed --noconfirm grub
sudo pacman -S --needed --noconfirm thunar
sudo pacman -S --needed --noconfirm brightnessctl
sudo pacman -S --needed --noconfirm hyprshot
sudo pacman -S --needed --noconfirm hyprpicker
