#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/metwas/Pictures/wallpapers/windows-11-flow-dark-mode-dark-background-pink-3440x1440-5747.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
